#!/bin/sh

if [ -e /var/clearos/protocol_filter/l7-protocols.cache ]; then
    logger -p local6.notice -t installer "app-protocol-filter-core - removing cache file"
    rm -f /var/clearos/protocol_filter/l7-protocols.cache
fi
